### ISSUE TITLE
kalama doesn't work on gentoo linux

### ISSUE THREAD

**Issue by etcnix** [jskalama/kalama#1]
Hello, corporateanon.
I've installed your application on my laptop with gentoo linux and it doesn't work.
After `gentoo ~ # npm -g install kalama` I get two warning messages:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/kalama/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```
When I'm trying to launch kalama I get an error:
```
etcnix@gentoo ~ $ kalama
module.js:471
    throw err;
    ^

Error: Cannot find module './build/main'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib64/node_modules/kalama/kalama.js:2:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
My system is:
```
gentoo ~ # uname -a
Linux gentoo 4.4.6-gentoo #3 SMP Thu Dec 29 15:18:13 EET 2016 x86_64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz GenuineIntel GNU/Linux
```

**Comment by corporateanon** [comment]
Hi. It's known bug. The build it's temporarily broken. I will fix it on
Monday and keep you updated.

10 марта 2017 г. 13:17 пользователь "test test" <notifications@github.com>
написал:

**Comment by corporateanon** [comment]
Fixed
